### ISSUE TITLE
I am a user of zephyrus s gx531gw. Help me

### ISSUE THREAD

**Issue by rudytt** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#1]
I have been trying a Mac as mojave 10.14.4 hack in tosh for 5 months now. But I still didn't succeed. Could you share those files with me if you succeeded in hack in tosh with that laptop? I am asking a question at the Korea Forum, but the information here is not enough to solve it. I want you to share the file if you succeed. I don't care whether it's a dmg+clover file or a gho file. I would appreciate it if you could give me a file to make a bootusb.

**Comment by rudytt** [comment]
I think my error sentences are like this 
Super IODevice: [Fatal] found unsupported ship ITE sequence ID=0xffff, Winbond sequence ID=0xffff

SMCSuperIo= ssio@failed to detect supported SuperIO chip

Super IODevice: [Fatal] found unsupported ship ITE sequence ID=0xffff, Winbond sequence ID=0xffff

How can i solve this problem?....

**Comment by williambj1** [comment]
Hi @rudytt !

Are you using my EFI right now?
If yes, you should make sure you are using your own DSDT instead of mine.
BTW, you can also update VirtualSMC as well, there is an update recently and I haven't updated it yet.
Another solution is to use FakeSMC instead, notice you'll need to patch your battery if you are not using VirtualSMC sets.

Hope this can help you!

**Comment by williambj1** [comment]
> I would appreciate it if you could give me a file to make a bootusb.

I personally use installing packed dmg(s) from Daliansky, he is a person like Rehabman in China, here is the [download link](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fblog.daliansky.net%2FmacOS-Mojave-10.14.4-18E226-official-version-with-Clover-4903-original-image.html).

**Comment by rudytt** [comment]
I made boot usb from gho files.

If you want to do this way, you need the following tools.
-Ghost.exe      (make for Boot usb used by xxx.gho files)
-Ghostexp.exe (editing boot files)

So what am I supposed to do? 
Isn't it the same laptop as me?
If you have the same laptop, give me a BootUSB file.
If I've translated it correctly, do you mean to take the file from the download link and try it?
Windows 10용 메일에서 보냄

보낸 사람: Bat.bat
보낸 날짜: 2019년 4월 22일 월요일 오후 9:40
받는 사람: williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531
참조: rudytt; Mention
제목: Re: [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531] I am a user ofzephyrus s gx531gw. Help me (#1)

I would appreciate it if you could give me a file to make a bootusb.
I personally use installing packed dmg(s) from Daliansky, he is a person like Rehabman in China, here is the download link.

**Comment by williambj1** [comment]
I know the ghost installing method but I strongly recommend you to use the DMG method, I'm not sure how the efi file is packed into you `.gho`, 
**Sure, download from that link, it is a clean installing mirror, don't worry about viruses.**
Please use popular installation methods. Otherwise, I'm truly unable to help you.

**Comment by rudytt** [comment]
I downloaded xxx.dmg file in your link. And I make bootUSB with balenaetcher.
But I don’t know in clover setting. So I take pictures. See this and tell me more 
Settings. 



Windows 10용 메일에서 보냄

보낸 사람: Bat.bat
보낸 날짜: 2019년 4월 23일 화요일 오후 7:47
받는 사람: williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531
참조: rudytt; Mention
제목: Re: [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531] I am a user ofzephyrus s gx531gw. Help me (#1)

I know the ghost installing method but I strongly recommend you to use the DMG method, I'm not sure how the efi file is packed into you .gho,
Sure, download from that link, it is a clean installing mirror, don't worry about viruses.
Please use popular installation methods. Otherwise, I'm truly unable to help you.

**Comment by rudytt** [comment]
I want to be able to choose my computer as a dual view of Windows 10 and Mojave. But I really need your help. As a result, I will allow you to support my laptop remotely. What do you think?

나의 iPhone에서 보냄

2019. 4. 23. 오후 7:47, Bat.bat <notifications@github.com> 작성:

**Comment by stonexing** [comment]
> I want to be able to choose my computer as a dual view of Windows 10 and Mojave. But I really need your help. As a result, I will allow you to support my laptop remotely. What do you think? 나의 iPhone에서 보냄 2019. 4. 23. 오후 7:47, Bat.bat <notifications@github.com> 작성:
> […](#)
> I know the ghost installing method but I strongly recommend you to use the DMG method, I'm not sure how the efi file is packed into you .gho, Sure, download from that link, it is a clean installing mirror, don't worry about viruses. Please use popular installation methods. Otherwise, I'm truly unable to help you. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

First. you need boot with -v and see the message on the screen when installer progress broken down. 
Then search this message by google.

**Comment by rudytt** [comment]
How can i upload pictures on this?

**Comment by rudytt** [comment]
This is error picture link.
https://drive.google.com/file/d/1GR70ExOlTqcD54x3P2RuY-JwvuughkwU/view?usp=drivesdk

**Comment by williambj1** [comment]
> How can i upload pictures on this?

Drag and drop is fine, it's hard for me to view things on google.

Are you sure you stuck here, btw, what is your NVMe harddisk?

You need to replace the EFI files with mine, remember to use your own DSDT

I don't think dual monitor with two systems at the same time is possible unless you use virtual machines. If you know a bit of computer operating systems,  you'll know that.

Finally, I strongly recommend you to read more guides, seems that you are a bit new in this field.
Keep learning and you will receive your succession.

**Comment by williambj1** [comment]
Please follow those instructions, otherwise the help request makes no scene. Closed for no respond.

**Comment by rudytt** [comment]
Hi i'm back. I downloaded the image from the download link you told me and created bootusb with ghost 32 in Windows environment. After deleting all the files uploaded here from the bootusb-efi-clover path, I boot only the downloaded epi file, and the screen is different from the previous one, but it still stops at the first installation screen. If possible, I think there will be a laptop like me. Please check if there is a reference book based on the video or Windows environment. I've already tried to get help from the image installation link, but it didn't work.

**Comment by williambj1** [comment]
@rudytt 
As I stated before, ghost 32 is not supported and not suitable for this EFI at all!
I have no idea about the `epi` you mentioned above.
Please use a standard installation, it is VERY easy, it makes your life much easier!!!
Again, please get rid of the repackaged ghost file, it's common to be extremely dirty with tones of unexpected issues. 
I'd strongly suggest you read some instruction in tonymacx86 or insanelymac.
