### ISSUE TITLE
HDMI / usb-c inquiry

### ISSUE THREAD

**Issue by ltanedo** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#11]
Hey great work with your EFI! Do you know if the HDMI port is working? Also can you use a usb-c to HDMI dongle on the usb-c port?  I'm considering getting the GX531 because of your work.

**Comment by williambj1** [comment]
@ltanedo 

Unfortunately, it doesn't since both the ports are connected to the Nvidia Graphics card which is not working in macOS.

duplicated with #10
