### ISSUE TITLE
About framebuffer patching & Wifi card replacement

### ISSUE THREAD

**Issue by trankimlonghai** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#15]
Hi, ah... one more thing to ask is... I am using an already config.plist from ton.yma.cx86 and yes obviously my hackintosh can work smoothy with Intel UHD 630 config from ton.ymac.x86 but I want to pratice patching for myself, I did, however, the problems after I patch (with Hackintool) are:
1. export as a config.plist then Hackintool will automatically replace / add the data I patched to the exist config.plist in EFI/CLOVER, so I also removed the old one in config.plist and then save -> restart and boot with new config => result: kernel panic OR the cursor lag when I move my mouse appears for about 10 - 15s when login screen shows up.

I don't know what's wrong here, I missed something in the patch ?

Moreover, can you suggest me the type and kind of wifi card that suite and okay for my Rog Strix G G531GU for running Hackintosh ? 😊

**Comment by Herrengit** [comment]
You have hackintosh now?  Rog Strix G
Can you adjust the keyboard light
