### ISSUE TITLE
Help with disabling discrete graphics card on G531GU (Rog Strix G) - GTX 1660ti

### ISSUE THREAD

**Issue by trankimlonghai** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#16]
Hi, do you have any suitable SSDT files to disable discrete graphics card for GTX 1660ti on Rog Strix G G531GU ? Or else, can you show me the way you did to disable discrete graphics card on your Hackintosh laptop ? Many thanks ! <3
(I tried some methods like use SSDT from Rehabman or try patching SSDT but I see nothing like example from guide of rehabman to disable), even when I managed to patch it, after booting to the system, I still see GTX 1660ti appears in system reports in about this mac.

**Comment by williambj1** [comment]
@trankimlonghai 

WhateverGreen's builtin disabler works shockingly well. The device even disappears in IORegistry.

See: https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/blob/master/OpenCore/OC/config.plist#L129-L130

**Comment by trankimlonghai** [comment]
> @trankimlonghai
> 
> WhateverGreen's builtin disabler works shockingly well. The device even disappears in IORegistry.
> 
> See: https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/blob/master/OpenCore/OC/config.plist#L129-L130
> 
> PS: Older versions of this EFI contain a working SSDT for disabling the discrete graphics card.

Ah ah you mean disable external gpu in Hackintool option (this is from whatevergreen kext?) If so I think I know how to try it out and check again to see if it works or not and report back for you later ^^. Many thanks !
