### ISSUE TITLE
Timeout to automatically boot to highlighted partition not working (CLOVER) !

### ISSUE THREAD

**Issue by trankimlonghai** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#17]
Hi, I have problem where timeout (countdown) is not working in CLOVER bootloader (I set timeout is 10 seconds) but when I restart / or shutdown and turn on again the computer I see no timeout, it's just menu boot and let me choose one of those partition to boot in, it will not automatically choose to boot for me (because timeout not appears to work)
I already have osxaptiov3 fix (replace for aptio because aptio also does not work) and emuvariable in drivers of CLOVER. All of them not help me at all.
Any solutions ?

**Comment by williambj1** [comment]
@trankimlonghai 

Try to open Clover's config.plist via VS Code or Xcode and find whether there is any duplicated entries for timeout. The timer works fine for me with my config.

OsxAptio makes no sense in 300 series mother boards. Enumeration is even a joke now since Native NVRAM can be fixed by exposing the hidden PMC device by SSDT.

**Comment by trankimlonghai** [comment]
> @trankimlonghai
> 
> Try to open Clover's config.plist via VS Code or Xcode and find whether there is any duplicated entries for timeout. The timer works fine for me with my config.
> 
> OsxAptio makes no sense in 300 series mother boards. Enumeration is even a joke now since Native NVRAM can be fixed by exposing the hidden PMC device by SSDT.

I've checked, no duplicate timeout found, when I open config.plist with Xcode and found this
https://imgur.com/a/np7eFQA

**Comment by trankimlonghai** [comment]
I solved it by resetting nvram using F11 CLOVER and also set defaultbootedvolume (lastbootedvolume) then restart, and voila ! Thanks ! :''P
