### ISSUE TITLE
您好，您的触控板怎么修好的呢

### ISSUE THREAD

**Issue by DongLinghe** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#18]
我的玩家国度枪神3用您的efi文件能使用触控板但是不能上网，我自己的efi想加入您触控板的功能，请问我该如何做？

**Comment by williambj1** [comment]
@DongLinghe  请问你用的是什么网卡？直接在我的 EFI 的基础上添加网卡驱动可能是个更好的选择

**Comment by DongLinghe** [comment]
> @DongLinghe 请问你用的是什么网卡？直接在我的 EFI 的基础上添加网卡驱动可能是个更好的选择，我这里 OpenCore 和其它功能已经趋近完美了，华硕的玩家国度笔记本 EFI 通用性很强

我的网卡是Realtek RTL8168H，麻烦您看下，另外这台机子合盖子不关灯只关屏幕能解决吗？

**Comment by williambj1** [comment]
@DongLinghe 

触摸板实际上是 VoodooI2C 的兼容性问题，I2C 的总线速度 `FMCN` 和 `SSCN` 如果无法从 BIOS 读出来 VoodooI2C 就会使用自带的值，但是这些自带的值是给 Skylake 用的，并不兼容 Coffee Lake。

华硕的 I2C 总线速度其实 BIOS 是提供的，但是默认没有开启，修改 DSDT 的 `USTP` 使其在 macOS 下永远返回 `true` 就可以了，具体参考 ***SSDT-I2CBus*** 和 `USTP->XSTP` 的重命名。

P.S. `USTP` 这个函数有点诡异，我可能会在最近换成别的方法，比如 OC-Little 里的 ***SSDT-I2C-Conf***

**Comment by DongLinghe** [comment]
@williambj1  谢谢大佬回复，触控板成功驱动！但是使用触控板无法拖动窗口，好像需要用力点按的都做不到，这个有办法吗

**Comment by williambj1** [comment]
这个就是驱动的问题了，需要压力的功能需要配合触摸板的按键

**Comment by DongLinghe** [comment]
@williambj1 还有一个问题，HDMI接口是无解吗

**Comment by williambj1** [comment]
@DongLinghe 

HDMI 无解，走的是独显，Type-C 也是独显，可以在 Windows 下验证，如果有其他问题可以单独开 Issue，独显问题我之前已经在别的 issue 回答过了
