### ISSUE TITLE
Makefile.sh execution failed downloading IntelBluetoothFirmware 

### ISSUE THREAD

**Issue by kunlapat** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#19]
I was trying to run Makefile.sh and got this error message. I have checked that my internet connection is good.

> [ ERROR ]: Failed to download resources from IntelBluetoothFirmware, please check your connection!
![Screen Shot 2563-02-12 at 19 55 01](https://user-images.githubusercontent.com/26522199/74336983-ff99e200-4dd1-11ea-93e2-dc552904854b.png)

**Comment by williambj1** [comment]
IntelBluetoothFirmware changed its packaging yesterday, you can delete it in the script and manually download it. I'll get this fixed as soon as possible. Thanks for mentioning!

**Comment by williambj1** [comment]
Should be fixed

**Comment by kunlapat** [comment]
I met a new Error message.

> [ ERROR ]: Failed to download resources from Lilu, please check your connection!
![Screen Shot 2563-02-12 at 20 27 58](https://user-images.githubusercontent.com/26522199/74339244-4be72100-4dd6-11ea-8367-1a6f91f968e0.png)

**Comment by williambj1** [comment]
I think you may reached the GitHub API rate limit. Execute the script with a flag `--NO_GH_API`

```shell
$ ./Makefile.sh --NO_GH_API
```

**Comment by kunlapat** [comment]
All worked fine now. Thanks a lot!
