### ISSUE TITLE
您是怎么解决休眠问题的呢

### ISSUE THREAD

**Issue by DongLinghe** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#20]
我的玩家国度枪神3的efi目前除了休眠和触控板还有键盘背光都解决了，您能指点下吗？我的efi文件在我的GitHub里

**Comment by williambj1** [comment]
我手上这台机器我没有尝试过休眠模式 25，睡眠一切正常，也没做额外的补丁

**请问你使用我的 EFI 是不是也是这样呢？**

**Comment by williambj1** [comment]
已在 https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/issues/21#issuecomment-592329784 确认
