### ISSUE TITLE
现在用您的efi只有键盘不能用240hz不能调的问题了

### ISSUE THREAD

**Issue by DongLinghe** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#21]
请问这个怎么解决

**Comment by williambj1** [comment]
@DongLinghe 

键盘不能用的话试试删掉 AsusSMC

240Hz 不能调我不清楚，我这里 144Hz 在 HIDPI 和非 HIDPI 下都能调节

![image](https://user-images.githubusercontent.com/45396585/75503748-832e1280-5a11-11ea-9660-405719238895.png)

**Comment by DongLinghe** [comment]
@williambj1 已经尝试删除asusSMC，但是没有效果，我自己的EFI里有asusSMC是可以用的，怀疑是您efi里关于键盘背光的设置导致的

**Comment by williambj1** [comment]
@DongLinghe 

EFI 里面没有任何与键盘背光灯相关的设置，没有 SSDT，AsusSMC 也是默认的

还有另一种可能，你的内置 USB 键盘的端口号和我的不一样，我在 USBPorts 里面屏蔽了无效端口，你删除 USBPorts.kext 试试

**Comment by DongLinghe** [comment]
@williambj1 您太厉害了！目前用您的efi非常完美！就连休眠都修好了，bug就是我的刷新率没了

**Comment by williambj1** [comment]
@DongLinghe 

你的 EFI 刷新率可调吗？🤷🏼‍♂️

**Comment by DongLinghe** [comment]
@williambj1 但是我观察了一下好像虽然不能调，但是默认240hz，也可以了

**Comment by williambj1** [comment]
@DongLinghe 

耗电可能是个问题哈哈，如果我之后有了方法我会和你分享，你如果解决了也请你在这里和我说一声，谢谢！
