### ISSUE TITLE
I need some advice for Zephyrus M GU502GU

### ISSUE THREAD

**Issue by kunlapat** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#22]
My device: Asus Zephyrus M GU505GU
- CPU: Intel Core i7-9750H
- Graphics: Intel UHD 630 and Nvidia GeForce GTX 1660Ti 6GB
- SSD: WD Blue (WDC WDS250G1B0C-00S6U0)

I previously installed using Clover EFI from this repo with Oralila Mojave 10.14.6 and everything is ok. Most of the features listed is functioning.

But I am just curious about my cpu is different from the model that has been titled in this repo. How do i know if the configuration is perfectly matched with this i7-9750h? If i have to change some configuration, where do I have to look for or which file(s)?

Thank you, and please let me know if you want more information.

**Comment by williambj1** [comment]
Well, to be honest, you need to observe or "play around" with the functions to know what is working well.

Use GitHub and your hands to create proper files. That's how I did it.

I strongly recommend you to not use Oralila macOS. Use the original version from App Store.

**Comment by kunlapat** [comment]
Do i need a real macbook to get the vanilla image?

**Comment by williambj1** [comment]
I edited my comments above, please recheck it.

**Comment by williambj1** [comment]
No, you don't and of course, you can do it that way.

Plenty of guides available on the Internet. It's fairly easy even in Windows. Try gibmacOS.

**Comment by kunlapat** [comment]
I see. Thanks again for replying. I'll look them up.

**Comment by williambj1** [comment]
Good luck, feel free to reopen if you have more question.
