### ISSUE TITLE
G531GU 基本完美 有几个问题请求大神解决一下

### ISSUE THREAD

**Issue by Herrengit** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#23]
我的机型是G531GU
配置是i7 9750 1660ti 16g 144hz的1080p屏幕
我用了最新的EFI
目前存在的问题是内置的扬声器没声音 试过在config注入id 无效
还有fn的映射问题 就是无法关闭键盘灯和调节屏幕亮度

关于键盘 我一开始是没驱动的
我就删除了usb那个驱动 加入了VoodooPS2Controller.kext 实现了驱动

**Comment by Herrengit** [comment]
删掉 AsusSMC 键盘可以驱动了
但是无法关闭键盘灯和调节屏幕亮度

**Comment by williambj1** [comment]
@Herrengit 

在能帮你之前我想问几个问题

1. 内置扬声器没声音，那么耳机有没有声音呢？
1. 最新的 EFI，你是指 Release 页面的，还是用 Makefile 下载的？
1. 使用 VoodooPS2 驱动键盘？？？华硕不会走回头路吧，我非常确定你删了也能继续使用。

--

- Fn 键是用 AsusSMC 驱动的，但是只有 10.14 有效
- 不同机型的 USB 口不一样，你需要自己定制 USB，可以看黑果小兵的教程，不定制睡眠会有问题需要内建键盘
- 屏幕亮度和 AsusSMC 没有一点关系，你应该是弄混了什么

**Comment by Herrengit** [comment]
1.耳机有声音
2.我是在Release下载的
3.对 我先用上EFI后 发现键盘无法驱动 我删除了USBPorts.kext驱动和AsusSMC 驱动 然后键盘就能驱动了 

然后抱歉 我说错了 我是指用fn+f7/F8 不能调节屏幕亮度

**Comment by Herrengit** [comment]
抱歉 我可能描述的不太好 我重新描述一下
我用了Release上面最新的EFI
进去系统后 耳机是有声音的 扬声器没有
发现键盘无法驱动 我先删除了USBPorts这个 加入了VoodooPS2Controller 键盘可以驱动了
后面又折腾了一下 删除掉了VoodooPS2Controller也删除AsusSMC驱动 键盘也可以驱动

现在剩下的问题就是扬声器没有声音 还有键盘无法通过快捷键去调节背光和屏幕亮度等
其他的基本没有什么问题 神奇的是 我睡眠了几分钟 都可以唤醒 睡眠应该没有问题
我找个时间测试长时间的睡眠有没有问题

**Comment by williambj1** [comment]
-> #24
