### ISSUE TITLE
G531 问题新帖 求解

### ISSUE THREAD

**Issue by Herrengit** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#24]
我用了Release上面最新的EFI
进去系统后 耳机是有声音的 扬声器没有
发现键盘无法驱动 我先删除了USBPorts这个 加入了VoodooPS2Controller 键盘可以驱动了
后面又折腾了一下 删除掉了VoodooPS2Controller也删除AsusSMC驱动 键盘也可以驱动

现在剩下的问题就是扬声器没有声音 还有键盘无法通过快捷键去调节背光和屏幕亮度等
其他的基本没有什么问题 神奇的是 我睡眠了几分钟 都可以唤醒 睡眠应该没有问题
我找个时间测试长时间的睡眠有没有问题

**Comment by williambj1** [comment]
@Herrengit 

扬声器没声音我暂时也没办法，你可以参考紫米和黑果小兵的教程定制声卡

快捷键是 AsusSMC 的兼容性问题，我这里也没法帮你解决，得等作者更新

**Comment by williambj1** [comment]
如果还有问题可以重新 open，不需要开新帖
