### ISSUE TITLE
Which Method that use for make A bootable USB

### ISSUE THREAD

**Issue by seyhaheng2** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#4]
olarila, Or use terminal for boot or unibeast

**Comment by williambj1** [comment]
@seyhaheng2 
Each one is fine, it's up to you. Just make sure don't use ghost.
BTW, use the release version instead, some files are missing in the code section.

**Comment by seyhaheng2** [comment]
how to patch dsdt file in clover? just i copy all your efi to my USB EFI but it's not working.

**Comment by williambj1** [comment]
@seyhaheng2 
Well, you should read those great instructions in Tonymacx86 about DSDT if you want.

Please don't just complain about `not working`, give me details so I can help you shoot the issue.

**Comment by williambj1** [comment]
Closed for no response
