### ISSUE TITLE
Question: Could this configuration work with 10.14.6?

### ISSUE THREAD

**Issue by highercomve** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#5]
I just both a Zephyrus S GX531 and I wanna try this Hackingtosh configuration (I'm new with this clover and Hackintosh configuration). But right now in the app store, I could find Mojave installer for the version 10.14.6, and maybe is not working is that version.

Because the support on the readme said `Supports from 10.13.6(17G2112) ~ 10.14.5(18F132)` 

Thank you very much and sorry for bothering with this kind of silly questions.

**Comment by williambj1** [comment]
@highercomve Sorry for taking a long time to respond. I was a bit busy these days.

The clover EFI files should work fine theoretically, I'm using a different version of EFI right now based on the version in the repo and it works well.

Recently I did a lot of changes in my local EFI, some features are added such as keyboard backlight control and native fn key support but I also faced some critical issues, I'll upload the new files when everything is stable.

**Comment by highercomve** [comment]
Awesome!!

I will receive my Zephyrus on August 18. And I will tested with 10.14.6 and see how it goes.

Thank you for sharing your configuration, this is gonna be my first Hackintosh :)

**Comment by williambj1** [comment]
@highercomve 
Now I'm sure it works

**Comment by highercomve** [comment]
Hi @williambj1 

The installation work, but I have random resets after finishing the installation. Did you suffer from those in a moment

**Comment by williambj1** [comment]
@highercomve 

I don't understand what does `random rests` mean.
Could you post a picture or a detailed description?

**Comment by highercomve** [comment]
Hello @williambj1 i couldn't make it work. Whenever I was using the laptop, after 1 minute or less the computer restart.
