### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by pikaplace** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#6]
Any idea on how to fix the audio! I installed everything but in audio output I have built-in internal speakers but no actual audio are produced. (Mic is working properly).

**Comment by williambj1** [comment]
@pikaplace 

Before we could do further debugging, could you provide the following information?

1. Which macOS version are you using?
1. Your laptop model
1. Your sound card model & its codec
1. Which EFI are you using?  (Mine or others)
1. Which bootloader are you using? (Clover or OpenCore)
1. Did you try replacing the kexts from the original release sources?

I suggest you to re-download the kexts from acidanthera and try again.

**And make sure you boot into macOS with a cold boot. (Not a restart from Windows)**.

**Make sure you injected a correct Layout ID**

Try rebuilding kernel cache and see if it solves the problem

```bash
    sudo kextcache -i/
````

**Comment by williambj1** [comment]
Closed due to no response
