### ISSUE TITLE
GX531GW无法使用

### ISSUE THREAD

**Issue by bbcclove** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#7]
直接使用GX531GS的config无法安装和进入系统，我使用安装U盘的config修改后可以安装和修改系统，但是键盘没有完美驱动，FN键没有驱动，声卡有图标也可调但是无声，只能连接蓝牙，触摸板无法驱动，HIDPI无法看见，键盘灯、亮度都不能通过键盘调节，麻烦帮忙看一下，谢谢
我的EFI文件,安装的是10.13.6
https://pan.baidu.com/s/1DXVA2faZxLezy_bE0HzZVw

**Comment by bbcclove** [comment]
> 直接使用GX531GS的config无法安装和进入系统，我使用安装U盘的config修改后可以安装和修改系统，但是键盘没有完美驱动，FN键没有驱动，声卡有图标也可调但是无声，只能连接蓝牙，触摸板无法驱动，HIDPI无法看见，键盘灯、亮度都不能通过键盘调节，麻烦帮忙看一下，谢谢
我的EFI文件
https://pan.baidu.com/s/1DXVA2faZxLezy_bE0HzZVw

**Comment by bbcclove** [comment]
声卡已解决，不能从win直接重启进入mac，开机直接进mac是有声音的，触摸板还是没办法，键盘调节屏幕和键盘灯还是不行

**Comment by bbcclove** [comment]
使用最新OC引导时。出现：OCS：Failed to parse real field of type 1

**Comment by williambj1** [comment]
@bbcclove 
请问能提供一下我 Clover 无法引导的一些排错信息吗，比如日志，-v 图等等，谢谢！我很乐意完善 GX531GW 的支持！

> 使用最新OC引导时。出现：`OCS：Failed to parse real field of type 1` 

这个问题我已经了解了，但是最近没时间细查，正常是可以引导的，但是要求是拔除所有外接设备(U 盘等等)，建议将 OC 放入 ESP 分区然后用 BIOS 自带的入口添加新引导项，注意添加的是 OC 的 BOOTx64.efi，我周末找时间开 Debug 版本看看日志。

---

> 不能从win直接重启进入mac

嗯，热启动的确有这个问题，似乎是 300 系主板声卡控制器在 macOS 上的 Bug，仿冒 100 系控制器可以解决，但是这个方案不太“干净”，建议还是关机冷启动比较好

---

> 触摸板还是没办法

这个可以参考这个 [SSDT](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/blob/master/Shared/ACPI/SSDT-I2CBus.dsl) 如果想深究原理可以讨论

---

> 键盘没有完美驱动，FN键没有驱动

这个需要依赖 AsusSMC 和其它附属 SDK (Lilu, VirtualSMC)，我的 EFI 里面已经包含了

---

> HIDPI无法看见

这个需要用一键 HIDPI 脚本开启，去 GitHub 搜索 HIDPI，点开 Star 最多的那个按照步骤走就可以了

---

> 键盘灯、亮度都不能通过键盘调节

这个也是 AsusSMC 提供的功能，注意 AsusSMC 暂时只支持 Mojave，我和作者已经联系了，Catalina 的支持很快就会有

---

最近实在太忙，看到你的 Issue 没有及时回复，实在抱歉，你的 EFI 我还没细看，我周末抽时间看一眼 :)

**Comment by bbcclove** [comment]
感谢回复。OC引导出现错误应该是我的黑苹果安装在移动硬盘上导致不能引导的，前两天刚刚换了10.15，现在用你的efi可以正常引导了，需要在config里加上change ec0 to ec字段就可以正常引导安装和开机，另外whatevergreen无法change gfx0 to igpu，需要打开这个才能调节亮度，触摸板现在可以正常使用，除了亮度无法使用fn键调节和hidpi外，其余都正常。

**Comment by williambj1** [comment]
@bbcclove 

> OC引导出现错误应该是我的黑苹果安装在移动硬盘上导致不能引导的

这个我会尽快修复

---

> 需要在config里加上change ec0 to ec字段

我已经仿冒 EC 了，不需要这个，直接用原始 EC 会导致开机概率性五国

---

> 另外whatevergreen无法change gfx0 to igpu，需要打开这个才能调节亮度

请确保使用 Acidanthera 提供的最新 Whatevergreen 和 Lilu，亮度可以直接注入至 `_SB` 或 `GFX0` 里面，不需要多余的重命名

---

> 除了亮度无法使用fn键调节和hidpi外

这些详见上面的回复

---

PS: 请问你用的就是我的 EFI 吗，好多问题都是我的 EFI 不存在的，谢谢

**Comment by bbcclove** [comment]
全部是用的你的EFI,就是config里加了那两条重命名，不然无法安装和进去系统 bbcclove2010 邮箱bbcclove2010@sina.cn 签名由 网易邮箱大师 定制 在2019年10月11日 13:37，Bat.bat 写道： @bbcclove OC引导出现错误应该是我的黑苹果安装在移动硬盘上导致不能引导的 这个我会尽快修复 需要在config里加上change ec0 to ec字段 我已经仿冒 EC 了，不需要这个，直接用原始 EC 会导致开机概率性五国 另外whatevergreen无法change gfx0 to igpu，需要打开这个才能调节亮度 请确保使用 Acidanthera 提供的最新 Whatevergreen 和 Lilu，亮度可以直接注入至 _SB 或 GFX0 里面，不需要多余的重命名 除了亮度无法使用fn键调节和hidpi外 这些详见上面的回复 PS: 请问你用的就是我的 EFI 吗，好多问题都是我的 EFI 不存在的，谢谢 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by williambj1** [comment]
> [EFI.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3716640/EFI.zip)

@bbcclove 你的 zip 文件是损毁坏的

![image](https://user-images.githubusercontent.com/45396585/66694627-0dd2d700-ece8-11e9-9db9-1254c2693541.png)

```bash
$ unzip /Users/$/Downloads/EFI.zip

Archive:  /Users/$/Downloads/EFI.zip
  End-of-central-directory signature not found.  Either this file is not a zip file, or it constitutes one disk of a multi-part archive.  In the latter case, the central directory and zip file comment will be found on the last disk(s) of this archive.
unzip:  cannot find zip file directory in one of /Users/$/Downloads/EFI.zip or
        /Users/$/Downloads/EFI.zip.zip, and cannot find /Users/$/Downloads/EFI.zip.ZIP, period.
```

能顺便发一下你的原始完整 ACPI 表集和 开机后的 ACPI 表吗，谢谢

![image](https://user-images.githubusercontent.com/45396585/66694618-f85dad00-ece7-11e9-99f3-16d61ed30abb.png)

**Comment by bbcclove** [comment]
好的，今天我用你的原版2.4的EFI文件都开机试过，开不了机，我记录了一下错误，换回我昨天的EFI

[原版EFI开机错误.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3720227/EFI.zip)
[EFI.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3720228/EFI.zip)

**Comment by bbcclove** [comment]
[acpi.acpi.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3720236/acpi.acpi.zip)

**Comment by williambj1** [comment]
@bbcclove 

我通过你发来的ACPI 做了一些研究，发现应该是 RTC 的问题，我的主板上使用的传统 RTC 而华硕在后来的型号上默认使用 `AWAC` (Time and Alarm Device) 来替代 RTC，但同时也保留了原有 RTC，只是被禁用了。

**这是比对的结果，左边是你的，右边是我的**

![image](https://user-images.githubusercontent.com/45396585/66696564-ad4f9400-ecff-11e9-8637-4c6a90369e37.png)

![image](https://user-images.githubusercontent.com/45396585/66696660-74fc8580-ed00-11e9-83bf-5a5ed21bbdaf.png)

---

你发来的引导后 DSDT 里面已经把 `RTC` 的 `_STA` 判断破解了，我检查了一下二进制查找替换确认是这个补丁的作用

![image](https://user-images.githubusercontent.com/45396585/66696723-f227fa80-ed00-11e9-999c-fca81d627f39.png)

这个补丁的作用是将 `STAS` 这个变量替换为 `0xFF`来强制启动 RTC，但是这个补丁从根本上来说破坏了 ACPI 规范应该避免使用

![image](https://user-images.githubusercontent.com/45396585/66696810-c48f8100-ed01-11e9-9dc3-702bdf1fd177.png)


Acidanthera 官方给出了两种更加干净且可在 OpenCore 下使用的方案: 
- https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-AWAC.dsl
- https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-RTC0.dsl

我非常乐意修复 `AWAC` 的问题，但是我现在手上缺少你的原始 ACPI 导致我不能判断哪种方案更合适，能麻烦在 Clover 启动界面按下 F4 提取吗，谢谢

PS: 之前你说一定要更名才能有亮度是你的 SSDT 出了问题，这个 SSDT 将 PNLF 注入到了 
![image](https://user-images.githubusercontent.com/45396585/66696858-336cda00-ed02-11e9-8b28-48aa3975e391.png)，这种破坏 ACPI 规范的补丁/SSDT应该避免使用（在 OC 里面如果这样使用会导致其它操作系统全部 ACPI Error）

**Comment by bbcclove** [comment]
[origin.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3720498/origin.zip)
多谢了

**Comment by williambj1** [comment]
@bbcclove 
最后得出结论，使用 [SSDT-AWAC](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-AWAC.dsl)

> RTC:

```swift
        Device (RTC)
        {
            Name (_HID, EisaId ("PNP0B00") /* AT Real-Time Clock */)  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                IO (Decode16,
                    0x0070,             // Range Minimum
                    0x0070,             // Range Maximum
                    0x01,               // Alignment
                    0x08,               // Length
                    )
                IRQNoFlags ()
                    {8}
            })
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If ((STAS == One))  <<========================
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (Zero)
                }
            }
        }
```

> AWAC

```swift
        Device (AWAC)
        {
            Name (_HID, "ACPI000E" /* Time and Alarm Device */)  // _HID: Hardware ID
            Name (WAST, Zero)
            Name (WTTR, Zero)
            Method (_PRW, 0, NotSerialized)  // _PRW: Power Resources for Wake
            {
                Return (GPRW (0x72, 0x04))
            }

            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If ((STAS == Zero)) <<========================
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (Zero)
                }
            }
```

所以我们在 `_OSI` 为 `Darwin` 时给 `STAS` 赋值 为 `1` 就好了

试试这个 Clover:

[Clover.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3720665/Clover.zip)

非常感谢你提供的这些文件！

**Comment by bbcclove** [comment]
使用这个CLOVER确实可以直接进入系统了，但是进入以后有一个问题，键盘不能使用，任何键都不起作用，只能使用鼠标操作，无法输入密码

**Comment by williambj1** [comment]
@bbcclove 请删掉 AsusSMC 再试试，谢谢，AsusSMC 在 10.15 有 Bug

**Comment by fy199701** [comment]
你好，我的机型也是gx531gw，根据您提供的clover文件顺利安装并进入了10.15，基本上完美，但是没有声音，我不是从windows重启进入的，是冷启动，连接蓝牙音箱有声音，但是笔记本没声音，这个是怎么回事呢？

**Comment by williambj1** [comment]
@fy199701 请问能提供一下这些信息吗？

## Hackintool 音频页面截图

![image](https://user-images.githubusercontent.com/45396585/66715584-93917800-edf7-11e9-993e-38ff18451057.png)

## 完整 IOReg

![image](https://user-images.githubusercontent.com/45396585/66715631-14507400-edf8-11e9-8b44-fae1bd6bad02.png)


下载 IORegistryExplorer **2.1 !!!!!!!!**, 打开之后左上角另存为然后压缩发上来，谢谢

**Comment by bbcclove** [comment]
@williambj1 我如果使用oc引导的话，是不是必须将系统安装在电脑内置硬盘？我现在的苹果系统是安装在移动硬盘上，EFI引导也是在移动硬盘上，开机时按ESC使用移动硬盘引导进入系统的

**Comment by williambj1** [comment]
@bbcclove 

OC 的引导项选则机制是默认在有扫描到的情况下将**非自生所在 EFI 分区的 Bootx64.efi** 作为默认引导项，而且默认引导项需要通过模拟 NVRAM 来修改，如果**其他**硬盘里面有其他引导工具或 macOS 以外的系统就会非常尴尬，我为了防止默认启动到外接设备禁用了外接设备的启动项扫描，并且隐藏了启动项选择，导致你现在直接使用 OC EFI 是不行的。

引导外接设备是完全可以的，但是要在我的 Config 的基础上做些修改：

- https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/blob/master/OpenCore/OC/config.plist#L563
  - 调整为 `True`

- https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/blob/master/OpenCore/OC/config.plist#L593
  - 调整为 `0`

**Comment by bbcclove** [comment]
@williambj1 已经好了，不用删除AsusSMC异性，换用的1.1.1版本的放进去键盘是可以使用的

**Comment by SherlockGougou** [comment]
@bbcclove @williambj1 哇塞！你们太用心了吧！我的机型也是531GW，想尝试一下。经过你们的讨论，现在531GW应该通过那种方式引导呢？可用的引导配置文件可以整理一下放到README中吗作者大大！！！

**Comment by bbcclove** [comment]
@SherlockGougou 你下载俩直接用，没多大问题

**Comment by fy199701** [comment]
麻烦看下怎么回事吧，谢谢了

**Comment by williambj1** [comment]
> [fy1997’s MacBook Pro.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3723953/fy1997.s.MacBook.Pro.zip)

你的 IOReg 开起来没问题，我不清楚你那里怎么回事

IOReg 里面显示 AppleHDA 已经在正确的 Layout ID 下正常加载

**Comment by williambj1** [comment]
> @bbcclove @williambj1 哇塞！你们太用心了吧！我的机型也是531GW，想尝试一下。经过你们的讨论，现在531GW应该通过那种方式引导呢？可用的引导配置文件可以整理一下放到README中吗作者大大！！！

引导文件都在 仓库里，点绿色按钮下载就好，下完按照 readme 在终端里操作，最新的 Release 还没有包含针对 GX531GW 的修复

**Comment by fy199701** [comment]
@bbcclove 真的很奇怪啊，我的麦克风是好的，可以正常和siri交流，我用隔空播放连接蓝牙设备播放音乐也是正常的，但是只有电脑扬声器一点声音也没有

**Comment by SherlockGougou** [comment]
> > @bbcclove @williambj1 哇塞！你们太用心了吧！我的机型也是531GW，想尝试一下。经过你们的讨论，现在531GW应该通过那种方式引导呢？可用的引导配置文件可以整理一下放到README中吗作者大大！！！
> 
> @SherlockGougou
> 
> 引导文件都在 仓库里，点绿色按钮下载就好，下完按照 readme 在终端里操作，~最新的 Release 还没有包含针对 GX531GW 的修复~，如果是第一次接触黑苹果建议从 Clover 入手，会简单一些
> 
> https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/releases/tag/v2.5.1
> 
> 来这里下载

感谢！！！辛苦了！！！

**Comment by bbcclove** [comment]
@williambj1 刚刚换回10.14，感觉比10.15更流畅了，而且切换大小写屏幕也有显示，比10.15方便许多，但是还存在问题，键盘控制亮度仍然无法实现，键盘背光无法调节，是否需要安装其他第三方软件？

**Comment by williambj1** [comment]
> @williambj1 刚刚换回10.14，直接使用您的kext可以驱动键盘灯和屏幕亮度键盘调节，基本完美，而且感觉10.14比10.15流畅，使用起来感觉好点，AsusSMC什么时候支持10.15，方便升级？另外OC我还没有试能不能引导10.14，明天试一试，不知道会不会卡logo

AsusSMC 的作者我已经联系了，应该很快，我用了一年 10.14 感觉 UI 的流畅度是整体不如 Catalina 的，Catalina 对 144Hz 的屏幕优化好很多

**Comment by bbcclove** [comment]
> > @williambj1 刚刚换回10.14，直接使用您的kext可以驱动键盘灯和屏幕亮度键盘调节，基本完美，而且感觉10.14比10.15流畅，使用起来感觉好点，AsusSMC什么时候支持10.15，方便升级？另外OC我还没有试能不能引导10.14，明天试一试，不知道会不会卡logo
> 
> AsusSMC 的作者我已经联系了，应该很快，我用了一年 10.14 感觉 UI 的流畅度是整体不如 Catalina 的，Catalina 对 144Hz 的屏幕优化好很多

您帮忙看了OC包没有，有没有问题，引导10.15无法成功？

**Comment by williambj1** [comment]
> > > @williambj1 刚刚换回10.14，直接使用您的kext可以驱动键盘灯和屏幕亮度键盘调节，基本完美，而且感觉10.14比10.15流畅，使用起来感觉好点，AsusSMC什么时候支持10.15，方便升级？另外OC我还没有试能不能引导10.14，明天试一试，不知道会不会卡logo
> > 
> > 
> > AsusSMC 的作者我已经联系了，应该很快，我用了一年 10.14 感觉 UI 的流畅度是整体不如 Catalina 的，Catalina 对 144Hz 的屏幕优化好很多
> 
> 您帮忙看了OC包没有，有没有问题，引导10.15无法成功？

OC 可以试试 Release 里面的版本吗，启动如果卡住请 **用 VS Code!!!** 在 **[这行](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/blob/master/OpenCore/OC/config.plist#L631)** 的两个 `><` 中间加上 `-v`. 

光反馈卡条我无法排错，谢谢！！

**Comment by bbcclove** [comment]
> > > > @williambj1 刚刚换回10.14，直接使用您的kext可以驱动键盘灯和屏幕亮度键盘调节，基本完美，而且感觉10.14比10.15流畅，使用起来感觉好点，AsusSMC什么时候支持10.15，方便升级？另外OC我还没有试能不能引导10.14，明天试一试，不知道会不会卡logo
> > > 
> > > 
> > > AsusSMC 的作者我已经联系了，应该很快，我用了一年 10.14 感觉 UI 的流畅度是整体不如 Catalina 的，Catalina 对 144Hz 的屏幕优化好很多
> > 
> > 
> > 您帮忙看了OC包没有，有没有问题，引导10.15无法成功？
> 
> @bbcclove
> 
> OC 可以试试 Release 里面的版本吗，启动如果卡住请 **用 VS Code!!!** 在 **[这行](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/blob/master/OpenCore/OC/config.plist#L631)** 的两个 `><` 中间加上 `-v`.
> 
> 光反馈卡条我无法排错，谢谢！！

已经解决了，是我太粗心，acpi加的SSDT-AWAC.aml这个没有加到config中去，现在oc已经引导进入了macos，但是为什么刚开机时无法选择win 系统，直接就进入了macos呢？而且clover引导可以键盘快捷键调节屏幕亮度和键盘等亮度，oc引导就没有了

**Comment by williambj1** [comment]
>> ...
> 
> 已经解决了，是我太粗心，acpi加的SSDT-AWAC.aml这个没有加到config中去，现在oc已经引导进入了macos，但是为什么clover引导可以FN+快捷键调节屏幕亮度和键盘灯亮度，oc引导就没有了？

@bbcclove

仓库里这个版本的 OC `MaxKernel` 和 `MinKernel` 功能有 Bug，Acidanthera 后来修复了但是我还没有更新，临时解决方案是把 AsusSMC `MaxKernel` 删掉

**Comment by bbcclove** [comment]
> > > ...
> > 
> > 
> > 已经解决了，是我太粗心，acpi加的SSDT-AWAC.aml这个没有加到config中去，现在oc已经引导进入了macos，但是为什么clover引导可以FN+快捷键调节屏幕亮度和键盘灯亮度，oc引导就没有了？
> 
> @bbcclove
> 
> 仓库里这个版本的 OC `MaxKernel` 和 `MinKernel` 功能有 Bug，Acidanthera 后来修复了但是我还没有更新，临时解决方案是把 AsusSMC `MaxKernel` 删掉

@williambj1 本来想照教程配置oc增加引导win等选项，结果debug文件里面找不到win的引导路径，oc和win引导都在esp里，debug里搜索不到Disk / Partition UUID，无法添加oc的引导选项，这是怎么会事？

**Comment by bbcclove** [comment]
@williambj1 AsusSMC最新1.2.0还不支持10.15吗？

**Comment by williambj1** [comment]
> @williambj1 AsusSMC最新1.2.0还不支持10.15吗？

暂时还不支持

---

> 本来想照教程配置oc增加引导win等选项，结果debug文件里面找不到win的引导路径，oc和win引导都在esp里，debug里搜索不到Disk / Partition UUID，无法添加oc的引导选项，这是怎么会事？

这个我还没有深入研究，理论上是可以的，试试把 Misc 的 `HideSelf` 关掉看看有没有入口出现

**Comment by bbcclove** [comment]
@williambj1 您好，现在使用最新的2.5.2引导的10.15.1，感觉电池驱动好像有点问题，原来100%的电量插着电源用到了95%，我把电源拔掉以后，正常使用到85%的电量，然后插上电源充电到88%就停止充电，现在用了一会电池电量掉到了87%，请问这是什么原因？

**Comment by williambj1** [comment]
@bbcclove 

试试老版本或者最新的 VirtualSMC 有没有问题 Ref: https://github.com/acidanthera/bugtracker/issues/539#issue-513881910

**Comment by bbcclove** [comment]
@williambj1 
使用最新版的VirtualSMC1.0.9版本解决问题，插电使用到现在还没有出现掉电情况，另外，将 Misc 的 HideSelf 关掉后，windows启动选项也出现了，谢谢

**Comment by bbcclove** [comment]
@williambj1 我改了前面那个路径以后，可以引导进入win，但是黑屏了，无法进入系统

**Comment by williambj1** [comment]
@bbcclove 

Hideself 关闭确实可以显示 Windows 但是由于我发现了一些问题，所以没有公开这个方法

### 问题如下

1. Windows 会由于 USTP -> XSTP 的补丁造成 Logo 转完圈直接黑屏，但是这个补丁是驱动触摸板用的
   - 解决方案1: 修改 VoodooI2C 里面的 I2C 总线速度预设值并自行编译一个版本（我知道怎么修改但是能我不想单独为此创建分支）
   - 解决方案2: 从 macOS 热启动至 Windows

2. OpenCore 引导出来的 Windows 机型会变成白苹果的信息，导致华硕的 Armoury Crate 和其他软件停止工作，得不偿失


PS: 现在 EFI 里面的 VoodooI2C 是开发组内部的一个魔改版本，GX531 使用官方版本需要在 Info,plist 里删除 pci8086,a368，否则会和 USB-C 控制器 [ANX7411](https://www.analogix.com/cn/products/usb-c-port-controller-power-delivery/anx7411) 发生冲突，造成开机 KP

**Comment by bbcclove** [comment]
@williambj1 OC引导win看来还是不是很成熟，就不折腾了，换CLOVER引导一段时间吧，现在使用中还有一些小问题希望帮忙解答一下：1、OC引导和四叶草引导在节能选项有不一样，OC有电能小憩，四叶草没有，我更换了电源SSDT-PLUG后才有，另外节能五项为什么始终只有三项，另外的两项是需要自己重新配置吗？2、音质的问题，现在声音虽然正常，但是音质听起来始终好像有杂音，没有win听起来好听，这是驱动没到位还是ssdt的原因？谢谢！

**Comment by williambj1** [comment]
@bbcclove 

> OC引导win看来还是不是很成熟

OC 的 Windows 引导已经定型，这个功能本身就不怎么适合 OEM 笔记本，有个比较骚的解决方案: 用 Clover 引导 OpenCore 再用 OpenCore 引导 macOS，OpenCore 技术交流群里有人实验成功里

---

> OC引导和四叶草引导在节能选项有不一样，OC有电能小憩，四叶草没有，我更换了电源SSDT-PLUG后才有

我这里两个是一样的，不清楚你那边什么问题，最新的 EFI 会这样吗?

---

> 另外节能五项为什么始终只有三项，另外的两项是需要自己重新配置吗

节能 5 项是针对台式机而言的，我朋友的 2018 款 MBP 15' 也只有 3 项

---

> 内置扬声器的音质似乎是有些问题，我一直没有时间重新定制，之前定制了一半，手上还有些整理的资料，如果你想根据黑果小兵的教程实践一下我可以把资料给你

**Comment by bbcclove** [comment]
@williambj1 好的，我下载了Ubuntu准备来研究一下，不过我时间不多，所以不知道什么时候能弄好，谢谢

**Comment by bbcclove** [comment]
这个电脑HDMI输出好像是2070显卡，这个有解吗？外接一个显示器无法使用

**Comment by williambj1** [comment]
@bbcclove 
USB-C 也是独显，可以在 Windows 下对着设置查看，无解

**Comment by bbcclove** [comment]
> @bbcclove
> 
> Hideself 关闭确实可以显示 Windows 但是由于我发现了一些问题，所以没有公开这个方法
> 
> ### 问题如下
> 1. Windows 会由于 USTP -> XSTP 的补丁造成 Logo 转完圈直接黑屏，但是这个补丁是驱动触摸板用的
>    
>    * 解决方案1: 修改 VoodooI2C 里面的 I2C 总线速度预设值并自行编译一个版本，这样就可以抛掉 USTP 补丁（我知道怎么修改但是能我不想单独为此创建分支）
>    * 解决方案2: 从 macOS 热启动至 Windows
> 2. OpenCore 引导出来的 Windows 机型会变成白苹果的信息，导致华硕的 Armoury Crate 和其他软件停止工作，得不偿失
> 
> PS: 现在 EFI 里面的 VoodooI2C 是开发组内部的一个魔改版本，GX531 使用官方版本需要在 Info,plist 里删除 pci8086,a368，否则会和 USB-C 控制器 [ANX7411](https://www.analogix.com/cn/products/usb-c-port-controller-power-delivery/anx7411) 发生冲突，造成开机 KP
> 
> Edit: VoodooI2C 需要修改的地方 [在这里](https://github.com/alexandred/VoodooI2C/blob/9e95e195a7e74464d2c41277b998c82a12eabf01/VoodooI2C/VoodooI2C/VoodooI2CController/VoodooI2CControllerDriver.cpp#L469-L473)
> 替换的值为 (注意进制转换)
> 
> ```
> ss_hcnt: 1010, ss_lcnt: 1085
> fs_hcnt: 257, fs_lcnt: 300, fs_sda_hold: 98
> ```

最新的VoodooI2C 2.3版本还需要删除a368这个吗？能否直接使用？

**Comment by williambj1** [comment]
@bbcclove 

> 最新的VoodooI2C 2.3版本还需要删除a368这个吗？能否直接使用？

依旧不行

![CB7E7983427A128494057C9EF0861926](https://user-images.githubusercontent.com/45396585/70857895-01f6d180-1f32-11ea-8316-68966b8bf1bf.jpg)

**Comment by bbcclove** [comment]
电脑已经用不下去了，买了个4K屏，看了以后回不去了，觉得这个电脑屏幕颗粒感太强，直接看不下去，所以想用HDMI外接，结果无解，现在USB的设备外接显示器最高只有4K/30HZ，不知道够不够用

**Comment by williambj1** [comment]
如果还有问题欢迎随时 Open 这个 Issue
