### ISSUE TITLE
键盘无法使用

### ISSUE THREAD

**Issue by unionpacificy** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#8]
您好！
我的机型是GX701，在你没有发布2.5.1之前，同样出现了@bbcclove的问题，即开机无法进入系统，唯一能进入系统的EFI为最初版本(initial version)，但是键盘无法使用（完全无响应）。
使用了2.5.1之后，可以完美进入系统，但是同样的，键盘无法使用（完全无响应），删除AsusSMC无法解决问题，更换旧版本的AsusSMC 1.1.1也同样无法驱动键盘（最新版AsusSMC也同样无法使用），甚为苦恼，因为没有驱动键盘就无法输入密码开机，什么都做不了。但是2.5.1能驱动触摸板，目测Hidpi也能正常使用，电池电量也能正常显示。
请问能麻烦看看吗？感激不尽！！

**Comment by unionpacificy** [comment]
Btw, 系统是Mojave10.14.6.
这是dsdt
[origin.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3752203/origin.zip)

**Comment by williambj1** [comment]
@unionpacificy 
试试在 EFI 中加入 [VoodooPS2](https://github.com/acidanthera/VoodooPS2)

**Comment by unionpacificy** [comment]
试过了 还是不行

**Comment by williambj1** [comment]
@unionpacificy 能提供一下你的 IOReg 和 Windows 下的 AIDA64 完整报告吗？谢谢

PS: 试试把 USBPorts.kext 删除

**Comment by unionpacificy** [comment]
[压缩文件.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3770924/default.zip)
@williambj1 我魔改了一下你的EFI，现在已经可以使用键盘了（我也不知为什么可以用...），但是用回你2.5.1的EFI还是不能使用键盘，删除USBPorts也没用。

我现在的EFI可以调整亮度，声音只有在冷启动时能用（即直接开机进入mac声音才正常，从windows重启没有声音），键盘可以驱动，触摸板也没有问题。但是Fn键不能用，Asus键盘灯不能控制。

讲道理v2.5.1稍作调整就可以完美驱动了，我也不知是哪个地方出的问题。。。估计IOReg应该看不出问题，因为现在的EFI可以驱动键盘，而用2.5.1系统都进不去所以也保存不了报告...

如果你有时间的话 我会提供所有必需文件 让这份EFI在冰刃系列更通用（至少加一个GX701...吧？)
谢谢你！

**Comment by williambj1** [comment]
@unionpacificy 

我看了你的 IOReg, 键盘是 USB HID 没问题。如果我猜的没错那就是 USB 定制问题了，但是删除 USBPorts 依然不行十分蹊跷

你把机型设置成了 MacBookPro 15,1 等于是直接让 USBPorts.kext 作废了，因为这个驱动是按照机型进行匹配的。

![image](https://user-images.githubusercontent.com/45396585/67566479-72ffe100-f75a-11e9-82ad-81a2b06e403e.png)

你的设备的 USB 键盘的内建端口位置和 GX531 不太一样，你的在 `HS08` 而 GX531 的在 `HS10`

![image](https://user-images.githubusercontent.com/45396585/67566612-dbe75900-f75a-11e9-9ca3-9b8731eb6959.png)

而 `HS08` 在 GX531 上我做了屏蔽处理所以不能使用是正常的

华硕冰刃系列的笔记本似乎都要定制 USB 把内建设备都正确定义才能睡眠，由于我手上并没有 GX701 请问有足够的能力自己定制 USB 吗，教程在[「这里」](https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html)

由于这里面涉及到不少技巧而且有个别内容在此时不太适用于我们的 EFI，如果方便的话能否发份邮件到我的邮箱然后加一下 QQ？谢谢！

**Comment by unionpacificy** [comment]
@williambj1 
Unfortunately I’m not able to find your email address on your home page....Could you please update your public email address via personal settings ?

Thank you!

**Comment by williambj1** [comment]
> @williambj1
> Unfortunately I’m not able to find your email address on your home page....Could you please update your public email address via personal settings ?
> 
> Thank you!

@unionpacificy 

I thought it was already visible, sorry about that.

- My Email is `williamjiang237@outlook.com`
- Or you could add my QQ if possible `MTg3Mjk0NDAxOA==` (Base64)
- If you are still uncomfortable maybe we could use a Gitter room

Thanks for your patience and its all up to you :)

**Comment by unionpacificy** [comment]
[USBMap.kext.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3828520/USBMap.kext.zip)

**Comment by williambj1** [comment]
Modified:
[USBMap-GX701.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/3828523/USBMap-GX701.zip)

**Comment by liuhxq990619** [comment]
@unionpacificy 您好，我的电脑也是 GX701GWR，即 i7-9750H / RTX 2070 版本，请问您方便分享一下您的 EFI 文件吗？我其实是偏小白一点，现在下载 @williambj1 编译好的 EFI 搭配黑果小兵的 10.15.2 镜像，无法进入安装界面，一直提示 previous shutdown cause 5，我也看不懂 -v 报告，想着求助您。万分感谢！

**Comment by williambj1** [comment]
@liuhxq990619 尝试删除 USBPorts.kext, 删除 USTP 重命名并提供 -v 图，谢谢

**Comment by williambj1** [comment]
如果需要帮助欢迎随时 Open 这个 Issue
